export { Burger as BurgerIcon } from './burger'
export { Dispositive as DispositivesIcon} from './dispositives'
export { Folder as FolderIcon } from './folder'
export { Home as HomeIcon } from './home'
export { Instlation as InstallationIcon} from './installation'
export { Laptop as LaptopIcon} from './laptop'
export { Meter as MeterIcon } from './meter'
export { Reconection as ReconectionIcon } from './reconection'
export { Router as RouterIcon } from './router'
export { Scale as ScaleIcon } from './scale'
export { Email as EmailIcon } from './email'
export { Phone as PhoneIcon } from './phone'